name: Expressjs Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 157.10.203.82
        username: root
        password: mO4X$Dl00*
        port: 22
        script: |
          cd web_ddos
          git fetch origin
          git checkout production
          git pull
          npm install
          pm2 reload web_ddos
